### ISSUE TITLE
VirtualizedList: You have a large list that is slow to update

### ISSUE THREAD

**Issue by bayramn** [fattahmuhyiddeen/react-native-complete-flatlist#13]
Thanks for the package. 

I have been trying hard to get rid of "VirtualizedList: You have a large list that is slow to update" warning when using FlatList in my react native expo app but I just couldn't resolve, even using "PureComponent" or React.memo. 

I tried your CompleteFlatlist package but issue is still present. Warning occurs when I switch tabs in BottomTabNavigation and it seems there is bug using together. Did you encounter such issues and how could I resolve it?

    `import * as React from "react";
      import { useEffect, useState, useContext, useMemo } from "react";
      import { View, Text, Button, SafeAreaView, FlatList, StyleSheet } from "react-native";
      import CompleteFlatList from "react-native-complete-flatlist";
      const MyBucket = ({ navigation }) => {
        const testQuotes = [
          { quote: "Quote 1", author: { name: "Author Name 1" }, _id: "1" },
          { quote: "Quote 2", author: { name: "Author Name 2" }, _id: "2" },
          { quote: "Quote 3", author: { name: "Author Name 3" }, _id: "3" },
        ];
        const cell = ({ data, index }) => {
          return <Text>{data.quote}</Text>;
        };
        return (
          <SafeAreaView style={styles.container}>
    
            <CompleteFlatList
              searchKey={["name", "status", "time", "date"]}
              pullToRefreshCallback={() => {
                alert("refreshing");
              }}
              data={testQuotes}
              renderSeparator={null}
              keyExtractor={(item) => item._id}
              renderItem={cell}
            />
          </SafeAreaView>
        );
      };
      const styles = StyleSheet.create({
        container: {
          flex: 1,
          marginTop: StatusBar.currentHeight || 0,
        },
        item: {
          padding: 20,
          marginVertical: 8,
          marginHorizontal: 16,
        },
        title: {
          fontSize: 32,
        },
      });

      export default MyBucket;
`

**Comment by fattahmuhyiddeen** [comment]
@bayram96 

i got some error when running your code. therefore I modified a little bit to get rid of the error

```
import * as React from "react";
  import { Text, SafeAreaView, StyleSheet } from "react-native";
  import CompleteFlatList from "react-native-complete-flatlist";
  const MyBucket = () => {
    const testQuotes = [
      { quote: "Quote 1", author: { name: "Author Name 1" }, _id: "1" },
      { quote: "Quote 2", author: { name: "Author Name 2" }, _id: "2" },
      { quote: "Quote 3", author: { name: "Author Name 3" }, _id: "3" },
    ];
    const cell = ({ item }) => {
      return <Text>{item.quote}</Text>;
    };
    return (
      <SafeAreaView style={styles.container}>
        <CompleteFlatList
          searchKey={["name", "status", "time", "date"]}
          data={testQuotes}
          keyExtractor={(item) => item._id}
          renderItem={cell}
        />
      </SafeAreaView>
    );
  };
  const styles = StyleSheet.create({
    container: {
      flex: 1,
      marginTop: 0,
    },
    item: {
      padding: 20,
      marginVertical: 8,
      marginHorizontal: 16,
    },
    title: {
      fontSize: 32,
    },
  });

  export default MyBucket;
```

But I could not manage to get the warning. Can you confirm if the problem still persist?

**Comment by fattahmuhyiddeen** [comment]
@bayram96 sorry my bad. I've updated the readme file after realizing the old sample code in the readme is no longer working. U can refer to the latest readme file

**Comment by bayramn** [comment]
@fattahmuhyiddeen thanks for taking time to resolve this. I don't think the warning comes from your package, it seems occur combination of using FlatList and BottomTabBar navigation. Warning appears as soon as switching bottom Tabs. I tried hard but I just couldn't resolve, even using "PureComponent" or React.memo.

[This](https://stackoverflow.com/questions/70059668/virtualizedlist-you-have-a-large-list-that-is-slow-to-update-warning-even-tho) question from stackoverflow seems to same issue with FlatList and Tab Navigation.

**Comment by fattahmuhyiddeen** [comment]
@bayram96 can u share your code so that I can simulate the warning?

**Comment by fattahmuhyiddeen** [comment]
closing this issue because this problem is related to RN's FlatList itself while this library is just extending it
