### ISSUE TITLE
fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by bayramn** [fattahmuhyiddeen/react-native-complete-flatlist#14]
I am trying build and publish my app but build throws error saying:

Arguments: ls-remote --tags --heads ssh://git@github.com/fattahmuhyiddeen/react-native-highlight-words.git
[stderr] Directory: /Users/expo/workingdir/build
[stderr] Output:
[stderr] fatal: Could not read from remote repository.
[stderr] 
[stderr] Host key verification failed.
[stderr] Please make sure you have the correct access rights
[stderr] and the repository exists.

It seems there is problem with dependency "react-native-highlight-words" while building but it doesn't any cause issue while in development. What can I do?

**Comment by fattahmuhyiddeen** [comment]
sorry @bayram96 i cant replicate the issue on my side

**Comment by fattahmuhyiddeen** [comment]
could not replicate and no reply
