### ISSUE TITLE
VirtualizedList missing keys form items

### ISSUE THREAD

**Issue by mfranceschini** [fattahmuhyiddeen/react-native-complete-flatlist#3]
Hello,

I'm getting this warning of missing keys when I use CompleteFlatList. I looked at the lib code and I think it's may be missing a keyExtractor property.

Do you have any ideia on this?

![screenshot_20180924-084902](https://user-images.githubusercontent.com/19409244/45951006-4833de00-bfd8-11e8-8d41-980910b41752.png)

Thanks in advance,
Matheus

**Comment by svenadlung** [comment]
I guess so too. I just added `keyExtractor={(item, index) => index.toString()}` to FlatList-component and it seems to work.

**Comment by fattahmuhyiddeen** [comment]
> `keyExtractor={(item, index) => index.toString()}`

Thank you. done added your code

**Comment by fattahmuhyiddeen** [comment]
This issue already fixed in version 1.1.23, thank you
