### ISSUE TITLE
How to get item and index inside the cell ?

### ISSUE THREAD

**Issue by Pruthvirajcodewave** [fattahmuhyiddeen/react-native-complete-flatlist#4]
In the fallowing code how to get the index of the list? 

cell(data) {
    return <Text>{data.name}</Text>;
  }

**Comment by fattahmuhyiddeen** [comment]
> In the fallowing code how to get the index of the list?
> 
> cell(data) {
> return {data.name};
> }

I already fix in version 1.1.23. you can do this now

cell(data,index) {
return {data.name + ' ' + index};
}

**Comment by fattahmuhyiddeen** [comment]
I even update the readme for u :D
