### ISSUE TITLE
Nested Data (searchKey)

### ISSUE THREAD

**Issue by alz10** [fattahmuhyiddeen/react-native-complete-flatlist#5]
My data will consist of nested objects (firebase database) so i tried the 'data' below to test if i can search using this plugin.  I nest `name: 'test'` inside `people: {}` and put people in searchKey array but i gave me an error (see pic below)

```
const data = [
  { people { name: 'test' }, status: 'Active', time: '8:10 PM', date: '1 Jan 2018' },
];

<CompleteFlatList
          searchKey={['people ', 'name', 'status', 'time', 'date']}
          highlightColor="transparent"
          renderSeparator={null}
          renderItem={this.cell}
          data={data}
        />
```

Am i doing it correctly? 

![45554167_2139632672957901_2292868604502212608_n](https://user-images.githubusercontent.com/38030623/48058401-2e56f080-e16b-11e8-95b8-ccaa9f550a9f.png)

**Comment by alz10** [comment]
This is what my firebase database look like. How can i search the datas in `ClassInfo`?
```
{
  "users": {
    "eYvMLhjB5TMrBsCEiYCwo8G4xiV2": {
      "ClassAttendance": {
        "-LQc3Xb5wvby7K_3zt2a": {
          "ClassInfo": {
            "classCourseSection": "jc",
            "classSchedule": "MTW",
            "classSubject": "uf",
            "classTimeEnd": "jv",
            "classTimeStart": "ig"
          }
        }
      }
    }
  }
}
```

**Comment by fattahmuhyiddeen** [comment]
Sorry, currently nested data search not yet supported. any PR is welcome

**Comment by fattahmuhyiddeen** [comment]
> This is what my firebase database look like. How can i search the datas in `ClassInfo`?
> 
> ```
> {
>   "users": {
>     "eYvMLhjB5TMrBsCEiYCwo8G4xiV2": {
>       "ClassAttendance": {
>         "-LQc3Xb5wvby7K_3zt2a": {
>           "ClassInfo": {
>             "classCourseSection": "jc",
>             "classSchedule": "MTW",
>             "classSubject": "uf",
>             "classTimeEnd": "jv",
>             "classTimeStart": "ig"
>           }
>         }
>       }
>     }
>   }
> }
> ```

@Albert0405 Sorry, currently nested data search not yet supported. actually I have no idea yet how to implement it. any PR is welcome.

For the time being, the best solution is the reformat your data to make it not nested. will that help?

**Comment by fattahmuhyiddeen** [comment]
@Albert0405 I already update the readme stating that nested data will not work for searching. can I close the issue?

**Comment by fattahmuhyiddeen** [comment]
closed due to the functionality requested (search nested key) is not the feature in this library. thank you. you may submit PR to improve this
