### ISSUE TITLE
load more data on scroll

### ISSUE THREAD

**Issue by naveedshahji** [fattahmuhyiddeen/react-native-complete-flatlist#6]
is there any way to load more data on scroll like we are doing in Flatlist
in FlatList we are doing it like onEndReached={()=> this._loadMore()}

**Comment by fattahmuhyiddeen** [comment]
Hi, thank you for using this library (version 1.1.31). I already update my code. Now you can use it like the one in example in the [readme](https://github.com/fattahmuhyiddeen/react-native-complete-flatlist/blob/master/README.md) (updated also)
```
onEndReached={() => console.log("reach end")}
onEndReachedThreshold={0}
```

**Comment by naveedshahji** [comment]
HI, thanks for making such a nice library. let me update it.

**Comment by fattahmuhyiddeen** [comment]
you are welcome

**Comment by naveedshahji** [comment]
I have           onEndReached={()=> this._loadMore()}
                    onEndReachedThreshold={0}
after second or third scroll I am getting the error like:
VirtualizedList: You have a large list that is slow to update - make sure your renderItem function renders components that follow React performance best practices like PureComponent, shouldComponentUpdate, etc. {"dt":13861,"prevDt":1498372326027,"contentLength":6624}

before, I were using flatlist and there was no such error and after shifting to "complete-flatlist" I am facing this issue. although I am using "React.PureComponent"

**Comment by fattahmuhyiddeen** [comment]
> I have onEndReached={()=> this._loadMore()}
> onEndReachedThreshold={0}
> after second or third scroll I am getting the error like:
> VirtualizedList: You have a large list that is slow to update - make sure your renderItem function renders components that follow React performance best practices like PureComponent, shouldComponentUpdate, etc. {"dt":13861,"prevDt":1498372326027,"contentLength":6624}
> 
> before, I were using flatlist and there was no such error and after shifting to "complete-flatlist" I am facing this issue. although I am using "React.PureComponent"

@naveedshahji can u share your code and also let me know how many data (number of indexes in the array) that supplied to the complete flatlist? thank you

**Comment by naveedshahji** [comment]
here is the code
   <CompleteFlatList
                  searchKey={['disorderness', 'reason']}
                  highlightColor="yellow"
                    data={this.state.vl}
                    onEndReached={()=> this._loadMore()}
                    onEndReachedThreshold={1}
                    // ItemSeparatorComponent= {this.ListViewItemSeparator}    
                    renderItem={this.cell}
                    keyExtractor={(item, index) => index.toString()}
                    ListFooterComponent={this.renderFooter}
                    ref={c => this.completeFlatList = c}
                    renderEmptyRow= {()=><Text>{''}</Text>}           
                />
 and loadmore is 
 _loadMore(){
           if(!this.state.isLoadingMore){
          this.setState({ isLoadingMore: true}); 
         if(this.state.lastVisible !== undefined) {
            this.unsubscribe = this.ref.where("id", "==", this.state.uid).orderBy('created', 'desc').startAfter(this.state.lastVisible)
            .limit(14).get().then(this.onCollectionUpdate);
           }
         } 
       }

I am loading 14 records on every scroll

**Comment by fattahmuhyiddeen** [comment]
@naveedshahji I have tested in new project, I got no warning. I put that project in new repo. can you modify the code until u get the warning?

you can push your code here https://github.com/fattahmuhyiddeen/testCompleteFlatlist/invitations

**Comment by naveedshahji** [comment]
@fattahmuhyiddeen thanks. sorry the error is not because of the "react-native-complete-flatlist" I have used many state variables before loading more. I am trying to optimize my code. thanks

**Comment by fattahmuhyiddeen** [comment]
> @fattahmuhyiddeen thanks. sorry the error is not because of the "react-native-complete-flatlist" I have used many state variables before loading more. I am trying to optimize my code. thanks

Glad to hear that. You are welcome
