### ISSUE TITLE
warning: ListView is deprecated and will be removed in a future release. 

### ISSUE THREAD

**Issue by naveedshahji** [fattahmuhyiddeen/react-native-complete-flatlist#7]
using this library I am getting the warning "ListView is deprecated and will be removed in a future release. "

**Comment by fattahmuhyiddeen** [comment]
you sure the warning causes by this library? You can check my source code. it is just written in single file. https://github.com/fattahmuhyiddeen/react-native-complete-flatlist/blob/master/index.js
No listview at all

**Comment by naveedshahji** [comment]
yes it is deprecated
