### ISSUE TITLE
how to clear search from outside click

### ISSUE THREAD

**Issue by naveedshahji** [fattahmuhyiddeen/react-native-complete-flatlist#8]
I have two buttons and on its click I want to load different data, which is loaded perfectly. but the text entered in search bar is not cleared. please help me how to clear the search text on button click. I want to clear the text before loading the data.

**Comment by fattahmuhyiddeen** [comment]
Ok please use latest version >= 1.1.33, I already update the[ README.md](https://github.com/fattahmuhyiddeen/react-native-complete-flatlist/blob/master/README.md), uca n scroll to the last section (methods), I have created ```clearSearch``` method

**Comment by naveedshahji** [comment]
this.completeFlatList.clearSearch(); only clear the search bar but the selection is not removing from the list. Now, the text is not showing in the search field but the search keywords is selected in the list.

**Comment by fattahmuhyiddeen** [comment]
> this.completeFlatList.clearSearch(); only clear the search bar but the selection is not removing from the list. Now, the text is not showing in the search field but the search keywords is selected in the list.

@naveedshahji really sorry. I overlooked that. Now already fixed in version 1.1.34. Thank you for reporting the bug. really appreciate it
