### ISSUE TITLE
Add Single/Multiple selection

### ISSUE THREAD

**Issue by Tilenozz** [fattahmuhyiddeen/react-native-complete-flatlist#9]
Fantastic project.
I'd like to suggest an idea.
Would be awesome if u can add single AND multiple selection (like a  radio button or check box with style Customizable ), appreciate if return an array.
And suggest , to set them as a props boolean ( like showSearch ).
Ofc this is only an idea. Anyway is already an awesome project. Congratulations

**Comment by fattahmuhyiddeen** [comment]
> Fantastic project.
> I'd like to suggest an idea.
> Would be awesome if u can add single AND multiple selection (like a radio button or check box with style Customizable ), appreciate if return an array.
> And suggest , to set them as a props boolean ( like showSearch ).
> Ofc this is only an idea. Anyway is already an awesome project. Congratulations

thnx for the suggestion, but quite busy now. maybe you can make a PR for that? Thanks

**Comment by Tilenozz** [comment]
Wrote a mail  @ fattahmuhyiddeen@gmail.com , so we can continue =)

**Comment by fattahmuhyiddeen** [comment]
thnks for your support

**Comment by fattahmuhyiddeen** [comment]
I'm going to close this issue since I have no time to work on this feature request. Thanks
